-- CreateEnum
CREATE TYPE "M1MUserPermission" AS ENUM ('VIEW_ALL_CONVERSATIONS', 'ASSUME_ATTENDANCE', 'TRANSFER_ATTENDANCE', 'CLOSE_ATTENDANCE', 'EDIT_CRM', 'VIEW_RECEIPTS', 'DELETE_CUSTOMERS', 'DELETE_MESSAGES', 'MANAGE_USERS', 'MANAGE_SECTORS', 'MANAGE_HOURS', 'MANAGE_AI', 'MANAGE_KNOWLEDGE', 'ACCESS_SETTINGS');

-- AlterTable
ALTER TABLE "m1m_users" ADD COLUMN     "permissions" "M1MUserPermission"[] DEFAULT ARRAY[]::"M1MUserPermission"[],
ADD COLUMN     "useCustomPermissions" BOOLEAN NOT NULL DEFAULT false;
