export const ATTENDANCE_STATES = {
  AI: "IA",
  HUMAN: "HUMANO",
  FINISHED: "FINALIZADO",
} as const;

export const ATTENDANCE_EVENT_TYPES = {
  STARTED_BY_AI: "STARTED_BY_AI",
  TRANSFERRED_TO_SECTOR: "TRANSFERRED_TO_SECTOR",
  TAKEN_BY_HUMAN: "TAKEN_BY_HUMAN",
  FINISHED_BY_HUMAN: "FINISHED_BY_HUMAN",
  FINISHED_BY_AI: "FINISHED_BY_AI",
} as const;
